
    spring:
        datasource:
            driverClassName: org.postgresql.Driver
            url: jdbc:postgresql://localhost:5432/payment-db
            jdbc-url: jdbc:postgresql://localhost:5432/payment-db
            username: postgres
            password: postgres 
