
    spring:
        datasource:
            driverClassName: org.postgresql.Driver
            url: jdbc:postgresql://${POSTGRES_URL}
            jdbc-url: jdbc:postgresql://${POSTGRES_URL}
            username: ${POSTGRES_USER}
            password: ${POSTGRES_PASSWORD}
